version: '3'

services:
    mongo_db:
      container_name: mongodb
      image: mongo:latest
      expose:
        - 27017
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db
        - ./etl_tools/mongodb_simulator/data:/collections_data
        - ./script/01-rs-initiate.js:/docker-entrypoint-initdb.d/01-rs-initiate.js
        - ./script/02-entrypoint.sh:/docker-entrypoint-initdb.d/02-entrypoint.sh
      command: ["--replSet", "dbrs", "--bind_ip_all"]

    postgre_db:
      image: postgres:13.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=db
      logging:
        driver: "json-file"
        options:
          max-file: "2"
          max-size: "500m"

volumes:
  mongo_data:
  postgres_data: